# Generated by Django 5.2.12 on 2026-04-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel'), ('entreprise', 'Entreprise')], max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TarifService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('verification_basique', 'Vérification basique'), ('rapport_complet', 'Rapport complet du terrain'), ('historique_complet', 'Historique complet'), ('certificat_verification', 'Certificat de vérification officiel'), ('depot_acd', 'Dépôt demande ACD'), ('depot_titre', 'Dépôt demande Titre Foncier'), ('depot_morcellement', 'Dépôt morcellement'), ('depot_reclamation', 'Dépôt réclamation'), ('abonnement_pro_mensuel', 'Abonnement Pro Mensuel'), ('abonnement_pro_annuel', 'Abonnement Pro Annuel'), ('abonnement_entreprise', 'Abonnement Entreprise')], max_length=50, unique=True)),
                ('prix', models.IntegerField(help_text='Prix en FCFA')),
                ('description', models.TextField()),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('montant', models.IntegerField(help_text='Montant en FCFA')),
                ('methode_paiement', models.CharField(blank=True, choices=[('cinetpay', 'CinetPay'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo'), ('wave', 'Wave'), ('carte_bancaire', 'Carte Bancaire')], max_length=30)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('succes', 'Succès'), ('echec', 'Échec'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('transaction_id_externe', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
