from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('terrains/', views.liste_terrains, name='liste_terrains'),
    path('terrains/<int:pk>/', views.detail_terrain, name='detail_terrain'),
    path('terrains/<int:pk>/rapport/', views.rapport_terrain, name='rapport_terrain'),
    path('terrains/verification/', views.verification_terrain, name='verification_terrain'),
    path('demandes/', views.mes_demandes, name='mes_demandes'),
    path('demandes/nouvelle/', views.nouvelle_demande, name='nouvelle_demande'),
    path('demandes/<int:pk>/', views.detail_demande, name='detail_demande'),
    path('reclamations/', views.mes_reclamations, name='mes_reclamations'),
    path('reclamations/nouvelle/', views.nouvelle_reclamation, name='nouvelle_reclamation'),
    path('admin-panel/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-panel/terrains/', views.admin_terrains, name='admin_terrains'),
    path('admin-panel/terrains/ajouter/', views.admin_ajouter_terrain, name='admin_ajouter_terrain'),
    path('admin-panel/terrains/<int:pk>/modifier/', views.admin_modifier_terrain, name='admin_modifier_terrain'),
    path('admin-panel/demandes/', views.admin_demandes, name='admin_demandes'),
    path('admin-panel/demandes/<int:pk>/', views.admin_detail_demande, name='admin_detail_demande'),
    path('admin-panel/utilisateurs/', views.admin_utilisateurs, name='admin_utilisateurs'),
    path('admin-panel/reclamations/', views.admin_reclamations, name='admin_reclamations'),
    path('admin-panel/alertes/', views.admin_alertes, name='admin_alertes'),
    path('admin-panel/statistiques/', views.admin_stats, name='admin_stats'),
    path('api/terrains/', views.api_terrains, name='api_terrains'),
    path('api/terrains/<int:pk>/', views.api_terrain_detail, name='api_terrain_detail'),
    path('api/communes/', views.api_communes, name='api_communes'),
    path('api/stats/', views.api_stats, name='api_stats'),
    path('api/notifications/', views.api_notifications, name='api_notifications'),
    path('terrains/export/', views.export_terrains_csv, name='export_terrains'),
    path('terrains/<int:terrain_pk>/upload/', views.upload_document, name='upload_document'),
    path('admin-panel/alertes/ajouter/', views.admin_ajouter_alerte, name='admin_ajouter_alerte'),
    path('admin-panel/alertes/<int:pk>/resoudre/', views.admin_resoudre_alerte, name='admin_resoudre_alerte'),
    path('admin-panel/reclamations/<int:pk>/update/', views.admin_update_reclamation, name='admin_update_reclamation'),
]
