# Generated by Django 5.2.12 on 2026-04-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('fraude_suspectee', 'Fraude suspectée'), ('vente_multiple', 'Vente multiple détectée'), ('document_falsifie', 'Document falsifié'), ('litige_actif', 'Litige actif'), ('non_conformite', 'Non-conformité')], max_length=30)),
                ('description', models.TextField()),
                ('est_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('region', models.CharField(default='', max_length=100)),
                ('latitude', models.FloatField(default=5.3484)),
                ('longitude', models.FloatField(default=-4.0267)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('type_demande', models.CharField(choices=[('acd', 'Demande ACD'), ('titre_foncier', 'Demande Titre Foncier'), ('morcellement', 'Morcellement'), ('mutation', 'Mutation / Transfert'), ('duplicata', 'Duplicata')], max_length=30)),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_cours', 'En cours de traitement'), ('complement_requis', 'Complément requis'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('finalisee', 'Finalisée')], default='soumise', max_length=30)),
                ('description', models.TextField()),
                ('commentaire_admin', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_finalisation', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFoncier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('titre_foncier', 'Titre Foncier'), ('acd', 'ACD'), ('plan_bornage', 'Plan de Bornage'), ('acte_vente', 'Acte de Vente'), ('permis_construire', 'Permis de Construire'), ('certificat_propriete', 'Certificat de Propriété'), ('autre', 'Autre')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='documents_fonciers/')),
                ('date_document', models.DateField()),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('est_officiel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('objet', models.CharField(max_length=300)),
                ('description_detaillee', models.TextField()),
                ('statut', models.CharField(choices=[('deposee', 'Déposée'), ('en_analyse', 'En analyse'), ('mediation', 'En médiation'), ('transmise_justice', 'Transmise à la justice'), ('resolue', 'Résolue'), ('classee', 'Classée sans suite')], default='deposee', max_length=30)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_cadastrale', models.CharField(max_length=50, unique=True)),
                ('superficie', models.FloatField(help_text='Superficie en m²')),
                ('statut', models.CharField(choices=[('libre', 'Libre / Disponible'), ('titre_foncier', 'Titré (Titre Foncier)'), ('acd', 'ACD en cours'), ('litige', 'En Litige'), ('reserve_etat', 'Réservé État'), ('lotissement', 'Lotissement en cours'), ('vendu', 'Vendu / Transféré')], default='libre', max_length=30)),
                ('adresse_complete', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geojson', models.TextField(blank=True, help_text='Données GeoJSON du contour')),
                ('numero_lot', models.CharField(blank=True, max_length=50)),
                ('ilot', models.CharField(blank=True, max_length=50)),
                ('zone_usage', models.CharField(choices=[('residentiel', 'Résidentiel'), ('commercial', 'Commercial'), ('industriel', 'Industriel'), ('agricole', 'Agricole'), ('mixte', 'Mixte')], default='residentiel', max_length=50)),
                ('valeur_estimee', models.BigIntegerField(blank=True, help_text='Valeur en FCFA', null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes_admin', models.TextField(blank=True)),
                ('alerte_active', models.BooleanField(default=False)),
            ],
        ),
    ]
