# Generated by Django 5.2.12 on 2026-04-03 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foncier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='signale_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeprocedure',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentfoncier',
            name='uploade_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiqueterrain',
            name='effectue_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quartier',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='foncier.commune'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='plaignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terrain',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foncier.commune'),
        ),
        migrations.AddField(
            model_name='terrain',
            name='proprietaire_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terrains_possedes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terrain',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foncier.quartier'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='foncier.terrain'),
        ),
        migrations.AddField(
            model_name='historiqueterrain',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='foncier.terrain'),
        ),
        migrations.AddField(
            model_name='documentfoncier',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='foncier.terrain'),
        ),
        migrations.AddField(
            model_name='demandeprocedure',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='foncier.terrain'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='foncier.terrain'),
        ),
    ]
